apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::940948267741:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::940948267741:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XWTYKQACAB48
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-25T16:31:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "11379"
  uid: 3b987b40-7fd7-4184-a9a6-d72a13c126c5
